# Generated by Django 6.0.5 on 2026-05-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.AlterField(
            model_name="amenity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="修正時間"),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="修正時間"),
        ),
    ]
