# Generated by Django 6.0.5 on 2026-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140, verbose_name="件名")),
                ("price_per_day", models.PositiveIntegerField(verbose_name="料金")),
                ("discription", models.TextField(verbose_name="紹介")),
                ("address", models.CharField(max_length=200)),
                (
                    "pets_allowd",
                    models.BooleanField(
                        default=True,
                        help_text="Does this house allow pets?",
                        verbose_name="ペット可",
                    ),
                ),
            ],
        ),
    ]
