# Generated by Django 6.0.5 on 2026-05-18 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="修正時間"),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=250)),
                ("explanation", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="修正時間"),
                ),
                ("name", models.CharField(max_length=250)),
                ("descrption", models.TextField()),
                ("country", models.CharField(default="JAPAN", max_length=50)),
                ("city", models.CharField(default="Tokyo", max_length=80)),
                ("price", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=250)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("perks", models.ManyToManyField(to="experiences.perks")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
