# Generated by Django 6.0.5 on 2026-05-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="修正時間"),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[("room", "Rooms"), ("experience", "experiences")],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
