# Generated by Django 6.0.5 on 2026-05-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[("room", "Rooms"), ("experience", "Experiences")],
                max_length=30,
            ),
        ),
    ]
