# Generated by Django 6.0.5 on 2026-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_alter_perks_options_experience_category"),
        ("rooms", "0004_room_category"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(blank=True, to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="room",
            field=models.ManyToManyField(blank=True, to="rooms.room"),
        ),
    ]
