# Generated by Django 6.0.5 on 2026-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
        ("rooms", "0005_alter_room_amenities_alter_room_category_and_more"),
        ("wishlists", "0002_alter_wishlist_experiences_alter_wishlist_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="room",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="rooms.room"
            ),
        ),
    ]
